# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisaRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('ci_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=17)),
                ('num_factura', models.IntegerField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Retira Cliente',
                'verbose_name_plural': 'Retira Cliente',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre_fun', models.CharField(blank=True, max_length=80, null=True)),
                ('ci_fun', models.IntegerField(blank=True, null=True)),
                ('importe', models.IntegerField()),
                ('cuotas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('num_factura', models.PositiveIntegerField(blank=True, null=True)),
                ('importe_cuota', models.FloatField()),
                ('control_adm', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pedido Compra',
                'verbose_name_plural': 'Pedidos Compra',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='PedidoPapeleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('Lapiceras', models.IntegerField(blank=True, null=True)),
                ('Clips', models.IntegerField(blank=True, null=True)),
                ('Lapiz', models.IntegerField(blank=True, null=True)),
                ('Grapas', models.IntegerField(blank=True, null=True)),
                ('ResmaA4', models.IntegerField(blank=True, null=True)),
                ('Sobre_carta', models.IntegerField(blank=True, null=True)),
                ('Tijera', models.IntegerField(blank=True, null=True)),
                ('Banda_elastica', models.IntegerField(blank=True, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=200, null=True)),
                ('Fecha_enviado', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido Papeleria',
                'verbose_name_plural': 'Pedido Papeleria',
                'ordering': ['date_create'],
            },
        ),
    ]
