# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FormulariosApp', '0001_initial'),
        ('FuncionariosApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdministracionApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopapeleria',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_ped_papeleria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidopapeleria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_ped_papeleria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='num_fun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FuncionariosApp.funcionarios'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_convenios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_convenios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avisaretiro',
            name='suc_retirar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.sucursales'),
        ),
        migrations.AddField(
            model_name='avisaretiro',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_retira_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avisaretiro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_retira_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
