# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdministracionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('numero_funcionario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cedula_funcionario', models.IntegerField()),
                ('nombre_funcionario', models.CharField(max_length=30)),
                ('apellido_funcionario', models.CharField(max_length=30)),
                ('sexo_funcionario', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('estado_funcionario', models.CharField(choices=[('Activo', 'Activo'), ('Deudor', 'Deudor'), ('Egreso', 'Egreso'), ('Seg_Paro', 'Seg_Paro'), ('Seg_Medico', 'Seg_Medico'), ('Nuevo Ingreso', 'Nuevo Ingreso')], max_length=30)),
                ('limite_saldo', models.IntegerField(blank=True, default=2500, null=True)),
                ('disponible_funcionario', models.FloatField(blank=True, default=0, null=True)),
                ('cargo_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.cargofuncionario')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.sucursales')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
