# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('fecha_error', models.DateField()),
                ('num_cajera', models.IntegerField()),
                ('num_boleta', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Errores Cajeras',
                'verbose_name_plural': 'Errores Cajeras',
            },
        ),
        migrations.CreateModel(
            name='Manuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre_manual', models.CharField(max_length=50)),
                ('manual', models.FileField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Manuales',
                'verbose_name_plural': 'Manuales',
            },
        ),
    ]
