# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Area de la empresa',
                'verbose_name_plural': 'Areas de la empresa',
            },
        ),
        migrations.CreateModel(
            name='CargoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre_cargo', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Cargo Funcionario',
                'verbose_name_plural': 'Cargo Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Comunicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('valor_promo', models.CharField(max_length=50)),
                ('descripcion_promo', models.CharField(max_length=200)),
                ('imagen_promo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alcance_promo', models.CharField(max_length=200)),
                ('estado_promo', models.BooleanField(default=False)),
                ('condiciones_promo', models.TextField(blank=True, max_length=200, null=True)),
                ('condiciones2_promo', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Comunicacion',
                'verbose_name_plural': 'Comunicaciones',
            },
        ),
        migrations.CreateModel(
            name='Financieras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre_financiera', models.CharField(max_length=20)),
                ('tel_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.CharField(max_length=200)),
                ('web_financiera', models.CharField(max_length=500)),
                ('usuario_finan', models.CharField(blank=True, max_length=50, null=True)),
                ('contraseña_finan', models.CharField(max_length=20)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Financiera',
                'verbose_name_plural': 'Financieras',
            },
        ),
        migrations.CreateModel(
            name='GrupoError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Grupo Error',
                'verbose_name_plural': 'Grupo Errores',
            },
        ),
        migrations.CreateModel(
            name='MediosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre_pago', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Medios de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField(max_length=2000)),
                ('respuesta', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='MotivoDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('motivoDevolucion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Motivo Dev',
                'verbose_name_plural': 'Motivo Dev',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('plataforma', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Plataformas',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='RegistroFraudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('num_pedido', models.IntegerField(unique=True)),
                ('fecha_venta', models.DateField()),
                ('importe', models.IntegerField()),
                ('ci_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('num_factura', models.IntegerField()),
                ('num_nc', models.IntegerField()),
                ('comentarios', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(default='Fraude', max_length=10)),
                ('estado_mercaderia', models.CharField(choices=[('Entregado', 'Entregado'), ('No entregado', 'No entregado')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('Descontado', 'Descontado'), ('No descontado', 'No descontado')], max_length=20)),
                ('liq_descuento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fraude',
                'verbose_name_plural': 'Fraudes',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('numero_suc', models.CharField(blank=True, max_length=3, null=True)),
                ('direccion_suc', models.CharField(max_length=60)),
                ('departamento_suc', models.CharField(blank=True, max_length=20, null=True)),
                ('zona_suc', models.CharField(blank=True, max_length=90, null=True)),
                ('encargado_suc', models.CharField(blank=True, max_length=90, null=True)),
                ('tel_suc', models.CharField(blank=True, max_length=20, null=True)),
                ('cel_suc', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_amex', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_anda', models.IntegerField(blank=True, null=True)),
                ('cod_cabal', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_club', models.IntegerField(blank=True, null=True)),
                ('cod_creditel', models.IntegerField(blank=True, null=True)),
                ('cod_creditosD', models.IntegerField(blank=True, null=True)),
                ('cod_diners', models.IntegerField(blank=True, null=True)),
                ('cod_lider', models.IntegerField(blank=True, null=True)),
                ('cod_maestro', models.IntegerField(blank=True, null=True)),
                ('cod_master', models.IntegerField(blank=True, null=True)),
                ('cod_sodexo', models.IntegerField(blank=True, null=True)),
                ('cod_oca', models.IntegerField(blank=True, null=True)),
                ('cod_passcard', models.IntegerField(blank=True, null=True)),
                ('cod_visa', models.IntegerField(blank=True, null=True)),
                ('cod_tarjetad', models.IntegerField(blank=True, null=True)),
                ('cod_edenred', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_retop', models.CharField(blank=True, max_length=10, null=True)),
                ('user_retop', models.CharField(blank=True, max_length=15, null=True)),
                ('pass_retop', models.CharField(blank=True, max_length=20, null=True)),
                ('link_retop', models.CharField(blank=True, max_length=500, null=True)),
                ('cod_pronto', models.CharField(blank=True, max_length=5, null=True)),
                ('user_pronto', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_pronto', models.CharField(blank=True, max_length=30, null=True)),
                ('link_pronto', models.CharField(blank=True, max_length=500, null=True)),
                ('cod_inforcheck', models.CharField(blank=True, max_length=5, null=True)),
                ('suc_inforcheck', models.CharField(blank=True, max_length=5, null=True)),
                ('clave_inforcheck', models.CharField(blank=True, max_length=10, null=True)),
                ('link_inforcheck', models.CharField(blank=True, max_length=500, null=True)),
                ('user_taxfree', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_taxfree', models.CharField(blank=True, max_length=30, null=True)),
                ('link_taxfree', models.CharField(blank=True, max_length=500, null=True)),
                ('user_itau', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_itau', models.CharField(blank=True, max_length=30, null=True)),
                ('link_itau', models.CharField(blank=True, max_length=500, null=True)),
                ('fondo_fijo1', models.PositiveIntegerField(blank=True, null=True)),
                ('fondo_fijo2', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['numero_suc'],
            },
        ),
    ]
