# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdministracionApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_sucursales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_sucursales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrofraudes',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.mediospago'),
        ),
        migrations.AddField(
            model_name='registrofraudes',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.plataforma'),
        ),
        migrations.AddField(
            model_name='registrofraudes',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_fraudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrofraudes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_fraudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_plataforma', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_plataforma', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motivodev',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_motivo_dev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motivodev',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_motivo_dev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_mensaje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_mensaje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediospago',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_medio_pago', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediospago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_medio_pago', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupoerror',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_grupoerror', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupoerror',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_grupoerror', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financieras',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_financiera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financieras',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_financiera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicaciones',
            name='medio_promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.mediospago'),
        ),
        migrations.AddField(
            model_name='comunicaciones',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_promocion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicaciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_promocion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargofuncionario',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_cargofun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargofuncionario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_cargofun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_area', to=settings.AUTH_USER_MODEL),
        ),
    ]
