# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdmConveniosApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitaboton',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_habilita_conv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habilitaboton',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_habilita_conv', to=settings.AUTH_USER_MODEL),
        ),
    ]
